<a href="https://colab.research.google.com/github/Nunesdejesus/Cursoemvideo-html5/blob/main/Criando_array_3D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# criar um array tridimensional (lista de tres dimensões)

# cada colchete aninhado representa uma dimensão do array

cubo = np.array([[[1, 4, 4],[3, 5, 2]],[[5, 6, 0],[7, 4, 1]],[[2, 8, 8],[0, 3, 6]]])
print('Array tridimensional:\n', cubo)

Array tridimensional:
 [[[1 4 4]
  [3 5 2]]

 [[5 6 0]
  [7 4 1]]

 [[2 8 8]
  [0 3 6]]]


In [ ]:
# Visualizar elementos especificos do cubo (Array tridimensional)
print('\nItem na posição 0,0,0:', cubo[0,0,0])
print('Item na posição 1,0,0:', cubo[1,0,0])
print('Item na posição 2,0,0:', cubo[2,0,0])


Item na posição 0,0,0: 1
Item na posição 1,0,0: 5
Item na posição 2,0,0: 2


In [ ]:
# Número de dimens~eos do array
print('número de dimensões do array cubo:', cubo.ndim)

# Dimensões do array
print('Tamanho do array cubo', cubo.shape)

# Número total do array
print('Total de elementos do array cubo:', cubo.size)

número de dimensões do array cubo: 3
Tamanho do array cubo (3, 2, 3)
Total de elementos do array cubo: 18


In [ ]:
import numpy as np
# Outro array tridimensional 2x3x3 (dois blocos, tres linhas e tres colunas)

tri = np.array([ [ [0,0,0],[1,1,1],[2,2,2] ],[ [4,4,4],[5,5,5],[6,6,6] ] ])
print(tri)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]


In [ ]:
# Imprimir os elementos do array usando iteração laços for
for i in range(2):
  for j in range(3):
    for k in range(3):
      print('Posição {0},{1},{2}: {3}'.format(i,j,k,tri[i][j][k]))

Posição 0,0,0: 0
Posição 0,0,1: 0
Posição 0,0,2: 0
Posição 0,1,0: 1
Posição 0,1,1: 1
Posição 0,1,2: 1
Posição 0,2,0: 2
Posição 0,2,1: 2
Posição 0,2,2: 2
Posição 1,0,0: 4
Posição 1,0,1: 4
Posição 1,0,2: 4
Posição 1,1,0: 5
Posição 1,1,1: 5
Posição 1,1,2: 5
Posição 1,2,0: 6
Posição 1,2,1: 6
Posição 1,2,2: 6


In [ ]:
# Criar um array com os números pares de 0 a 100
pares = np.array([n for n in range(0,101,2)])
print(pares)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
