<a href="https://colab.research.google.com/github/Nunesdejesus/Cursoemvideo-html5/blob/main/vetor_ou_array_de_uma_dimens%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

números = np.array([2, 6, 7, 9, 0, 1, 2, 5, 6, 8])

print(números[-1])
print(números.dtype)

números[0] = 3
print(números[0])

8
int64
3


**Array bidimensional**

In [ ]:
# array bidimensional com numpy

M = np.array([[1, 3, 5],[2, 4, 6],[3, 5, 7]])
print(M)


[[1 3 5]
 [2 4 6]
 [3 5 7]]


In [ ]:
print(M[0, 1])

3


In [ ]:
M[0, 1] = 7
print(M[0, 1])

7


In [ ]:
print(M)

[[1 7 5]
 [2 4 6]
 [3 5 7]]


In [ ]:
# visualizar uma coluna inteira

print('primera coluna:', M[:, 0])
print('segunda coluna:', M[:, 1])

primera coluna: [1 2 3]
segunda coluna: [7 4 5]


In [ ]:
# visualizar linha inteira
print('segunda lina', M[1,:])

segunda lina [2 4 6]


In [ ]:
# número de dimensão de um array
print(números.ndim)
print(M.ndim)

1
2


In [ ]:
# tanho de um array
print(números.shape)
print(M.shape)

(10,)
(3, 3)


In [ ]:
#Número de elementos de um array
print(números.size)
print(M.size)

10
9
